"""Update events model. Add img column

Revision ID: 11ecac5dc0a7
Revises: 707e138a89dc
Create Date: 2024-08-10 07:32:55.748355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ecac5dc0a7'
down_revision: Union[str, None] = '707e138a89dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'img')
    # ### end Alembic commands ###
