"""Update events model

Revision ID: 707e138a89dc
Revises: cb2707380cd5
Create Date: 2024-08-08 13:20:47.908611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '707e138a89dc'
down_revision: Union[str, None] = 'cb2707380cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('events', sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('events', 'date')
    op.drop_column('events', 'is_active')
    # ### end Alembic commands ###
